# -------------------------
# 📄 action.yml
# -------------------------
name: 'helm-upgrade'
description: 'Helm upgrade GitHub Action with full CLI support'
author: 'Dhruv Bundheliya'

branding:
  icon: anchor
  color: gray-dark

inputs:
  release:
    required: true
    description: 'Release name'
  chart:
    required: true
    description: 'Chart path, reference, or URL'
  namespace:
    required: false
    default: 'default'
  version:
    required: false
    default: ''
  create_namespace:
    required: false
    default: 'false'
    description: 'If set to true, will pass --create-namespace to Helm'
  wait:
    required: false
    default: 'false'
  atomic:
    required: false
    default: 'false'
  install:
    required: false
    default: 'true'
  dry_run:
    required: false
    default: 'false'
  reuse_values:
    required: false
    default: 'false'
  reset_values:
    required: false
    default: 'false'
  timeout:
    required: false
    default: '5m0s'
  cleanup_on_fail:
    required: false
    default: 'false'
  dependency_update:
    required: false
    default: 'true'
  values:
    required: false
    default: ''
  set:
    required: false
    default: ''
  set_string:
    required: false
    default: ''
  set_file:
    required: false
    default: ''
  post_renderer:
    required: false
    default: ''
  post_renderer_args:
    required: false
    default: ''
  kubeconfig:
    required: true
    description: 'Base64 encoded kubeconfig'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Run Helm Upgrade Script
      run: python ${{ github.action_path }}/main.py
      shell: bash
      env:
        INPUT_RELEASE: ${{ inputs.release }}
        INPUT_CHART: ${{ inputs.chart }}
        INPUT_NAMESPACE: ${{ inputs.namespace }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_CREATE_NAMESPACE: ${{ inputs.create_namespace }}
        INPUT_WAIT: ${{ inputs.wait }}
        INPUT_ATOMIC: ${{ inputs.atomic }}
        INPUT_INSTALL: ${{ inputs.install }}
        INPUT_DRY_RUN: ${{ inputs.dry_run }}
        INPUT_REUSE_VALUES: ${{ inputs.reuse_values }}
        INPUT_RESET_VALUES: ${{ inputs.reset_values }}
        INPUT_TIMEOUT: ${{ inputs.timeout }}
        INPUT_CLEANUP_ON_FAIL: ${{ inputs.cleanup_on_fail }}
        INPUT_DEPENDENCY_UPDATE: ${{ inputs.dependency_update }}
        INPUT_VALUES: ${{ inputs.values }}
        INPUT_SET: ${{ inputs.set }}
        INPUT_SET_STRING: ${{ inputs.set_string }}
        INPUT_SET_FILE: ${{ inputs.set_file }}
        INPUT_POST_RENDERER: ${{ inputs.post_renderer }}
        INPUT_POST_RENDERER_ARGS: ${{ inputs.post_renderer_args }}
        INPUT_KUBECONFIG: ${{ inputs.kubeconfig }}
